### ISSUE TITLE
Try super free not dark

### ISSUE THREAD

**Issue by RoyBergervoet** [CoryDerGrosse/Dark-Duolingo#1]
It seems the `Ekspr` class interferes with the dark styling of the page. If i disable the `background-color: rgb(var(--color-snow))!important;` in the `Ekspr` class, the dark theme works fine. 

By default:
![image](https://github.com/CoryDerGrosse/Dark-Duolingo/assets/49840967/92c9263b-d7e7-4ae6-9490-ca9ae83cb440)

With the aforementioned line disabled:
![image](https://github.com/CoryDerGrosse/Dark-Duolingo/assets/49840967/9372a57f-3e53-4ecc-94a4-6f3a22d73e22)

**Comment by Albrumn** [comment]
@RoyBergervoet
Thanks so much for pointing this out!  I ended up buying Super last year.  So, I don't see this ad on my account anymore.  I went ahead and created an alt account to test this.  I have corrected the issue along with a number of other styling issues.

Version 1.10 is available on Firefox now and will be available on Chrome as soon as it passes review.

Thanks again!
-Cory
